### ISSUE TITLE
SafeSearch kwarg

### ISSUE THREAD

**Issue by kuhanaklobasa** [Naught0/asyncurban#4]
It would be nice if we had a SafeSearch kwarg or something which whole concept would be that it doesn't send out the response if it contains bad words (nsfw) and instead uses another definition and checks that and so on until it finds one without bad words.

**Comment by Naught0** [comment]
I like this idea, however I think it would be best to leave that kind of filtering to the implementation of the library in your app. Urban dictionary is very NSFW by default and the API does not itself offer functionality like this. 

That said if this becomes highly requested I may reconsider just for ease of use.
